version: "3"
services:
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        container_name: express-react-client
        image: react
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
        links:
            - api
        networks:
            - webappnetwork

    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
        container_name: express-react-api
        image: express
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api:delegated
        depends_on:
            - mongodb
        command: bash -c "/usr/wait-for-it.sh --timeout=0 mongodb:27017 && npm run watch"
        networks:
            - webappnetwork

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
